<?php
/*
 * @file
 * code for resume module
*/
function uc_clickandpledge_form_alter(&$form,\Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    /* @var Drupal\Core\Entity\FieldableEntityInterface $entity */
    //loading scripts
	//$form['#attached']['library'][] = 'commerce_cnp/cnp-scripts';
	
	//change configuration button name
	$form['#attached']['library'][] = 'uc_clickandpledge/cnp_uc_credit.styles';
	
	if($form_id == "cnpuber_settings_form")
	{
		$form['actions']['submit'] = array(
			'#type' => 'submit',
			'#name' => 'verify',
			'#value' => t('Get the code'),
			'#attributes' =>array("id"=>"cnpauth"),
			//'#attributes' =>array("id"=>"cnpauth",'onsubmit' => 'return cnpValidate()'),
		);
		
		/*$form['actions']['submit'] = array(
			'#type' => 'submit',
			'#name' => 'swdu',
			'#value' => t('Signin with different user'),
			'#attributes' =>array("id"=>"signinwithdifferentuser"),
			
		);*/
		
	}
	if($form_id =="cnp-main-settings")
	{
		$form['edit-cnp-accid']['#validated'] = TRUE;
		$form_state['rebuild'] = TRUE;
	}
	
	if($form_id == 'commerce-checkout-flow-multistep-default'){
    if(!empty($form['commerce_payment'])){
      $payment_methods = $form['commerce_payment']['payment_methods']['#value'];
      $order = $form_state['order'];
      $order_wrapper = entity_metadata_wrapper('commerce_order', $order);

      $order_total = $order_wrapper->commerce_order_total->amount->value();

      if($order_total > 0){
        if(!empty($payment_methods) && array_key_exists('commerce_payment_zero|commerce_payment_commerce_payment_zero', $payment_methods)){
          unset($form['commerce_payment']['payment_method']['#options']['commerce_payment_zero|commerce_payment_commerce_payment_zero']);
        }
      }
      else{
        $form['commerce_payment']['payment_method']['#default_value'] = 'commerce_payment_zero|commerce_payment_commerce_payment_zero';
        $form['commerce_payment']['#attributes']['class'][] = 'commeprce_payment_pane_hide';
      }


    }
  }
	
}






?>

